# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Vibrato CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Create Env
      run: |
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .development.env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .development.env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .development.env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .development.env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .development.env
        echo "SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}" >> .development.env
        echo "SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}" >> .development.env
        echo "FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }}" >> .development.env
        echo "FIREBASE_PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY }}" >> .development.env
        echo "FIREBASE_PRIVATE_KEY_ID=${{ secrets.FIREBASE_PRIVATE_KEY_ID }}" >> .development.env
        echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .development.env
      
    - name: Run Tests (Jest)
      run: npm test

    - name: Build project
      run: npm run build

    - name: Deploy
      if: github.ref == 'refs/heads/main'
      run: npm run start
